/* J7Tracker 中文界面 — 文案字典
 * 规则：key 为页面上的英文文案（去掉首尾空白、内部空白折叠为单个空格后精确匹配，大小写不敏感兜底），
 *       value 为中文。REGEX 里是需要带数字/变量的模式。
 * 只翻译界面文案；推文正文、币名、账号名由 content.js 的排除规则跳过。
 */
window.__J7_ZH = {
  exact: {
    /* ===== 登录页 / 首页 ===== */
    "Join the Discord": "加入 Discord",
    "The fastest tracker": "最快的追踪器，",
    "for": "为",
    "snipers": "狙击手",
    "deployers": "发币者",
    "traders": "交易者",
    "degens": "赌狗",
    "devs": "开发者",
    "builders": "建设者",
    "Sub-10ms server-side deploys. Social-media tracking under 200ms. Built for traders who can't afford to be a second late.": "服务端发币低于 10ms，社媒追踪低于 200ms。为一秒都输不起的交易者打造。",
    "Monthly Users": "月活用户",
    "Tokens Deployed": "已发代币",
    "Total Volume": "总成交量",
    "Login": "登录",
    "Username": "用户名",
    "Password": "密码",
    "Remember me": "记住我",
    "No account? Join": "没有账号？加入",
    "for free credentials.": "免费领取凭证。",
    "No account? Join discord.gg/j7tracker for free credentials.": "没有账号？加入 discord.gg/j7tracker 免费领取凭证。",
    "Logging in...": "登录中...",
    "Invalid username or password": "用户名或密码错误",
    "You need to enable JavaScript to run this app.": "需要启用 JavaScript 才能运行此应用。",

    /* ===== 顶栏 ===== */
    "Manage Tracked Accounts": "管理追踪账号",
    "Settings": "设置",
    "Tracker & Feed Settings": "追踪器与信息流设置",
    "Automations": "自动化",
    "Pop Out Feed": "弹出信息流",
    "Pop out": "弹出",
    "Games": "游戏",
    "Vamp": "复刻",
    "Vamp Coin": "复刻代币",
    "Create": "创建",
    "Create a new token": "创建新代币",
    "Deploy Settings": "发币设置",
    "Deploy Settings, Wallets & Referrals": "发币设置、钱包与推荐返佣",
    "Site Chat..": "站内聊天..",
    "Site Chat": "站内聊天",
    "Unlock Sound": "启用声音",
    "Waiting for tweets...": "等待推文...",
    "PAUSED": "已暂停",
    "Paused": "已暂停",

    /* ===== 推文卡片 ===== */
    "DEPLOY": "发币",
    "Deploy": "发币",
    "Deploy token from this tweet": "用这条推文发币",
    "Vamp - Copy another token's data with this tweet's URL": "复刻 — 复制另一个代币的数据并使用这条推文的链接",
    "Instant deploy": "一键发币",
    "Quote": "引用",
    "Disable Suggestions": "关闭建议",
    "Disable AI Suggestions": "关闭 AI 建议",
    "Enable Suggestions": "开启建议",
    "Getting Image Suggestions..": "正在获取图片建议..",
    "Getting Image Suggestions...": "正在获取图片建议...",
    "Getting Suggestions...": "正在获取建议...",
    "No suggestions": "暂无建议",
    "Edit: N focuses name, T focuses ticker": "编辑：N 聚焦名称，T 聚焦代码",
    "Edit and focus name": "编辑并聚焦名称",
    "Edit and focus ticker": "编辑并聚焦代码",
    "View": "查看",
    "Retweet": "转推",
    "Reply": "回复",
    "Deleted": "已删除",
    "🗑️ DELETED": "🗑️ 已删除",
    "Followed": "已关注",
    "Pinned": "置顶",
    "Translate": "翻译",
    "Translate to English": "翻译为英文",
    "More translate languages": "更多翻译语言",
    "Translating...": "翻译中...",
    "Show original": "显示原文",
    "Hide": "隐藏",
    "Scan @": "扫描 @",
    "posts": "条帖子",
    "Followers": "粉丝",
    "Following": "关注中",
    "Joined": "加入于",
    "Article": "文章",
    "Click to read": "点击阅读",
    "Verified account": "已认证账号",
    "Business account": "企业账号",
    "Show more": "展开",
    "Show less": "收起",
    "Copied!": "已复制!",
    "Copied": "已复制",
    "Copy": "复制",
    "Open in X": "在 X 中打开",
    "Open on X": "在 X 中打开",
    "Open tweet": "打开推文",
    "Hide account": "隐藏账号",
    "Unhide account": "取消隐藏账号",
    "Add note": "添加备注",
    "Edit note": "编辑备注",
    "Scan account": "扫描账号",
    "Expand": "展开",
    "Collapse": "收起",
    "Download image": "下载图片",
    "Copy image": "复制图片",
    "Copy URL": "复制链接",
    "Copy link": "复制链接",
    "Copy text": "复制文字",
    "Crop": "裁剪",
    "Search image": "搜索图片",
    "Search Google": "搜索 Google",
    "Mute": "静音",
    "Unmute": "取消静音",
    "Muted": "已静音",
    "Block": "屏蔽",

    /* ===== 底栏 ===== */
    "Connected": "已连接",
    "Disconnected": "已断开",
    "Reconnecting...": "重新连接中...",
    "Connecting...": "连接中...",
    "Layout": "布局",
    "History": "历史",
    "Fees": "费用",
    "Theme": "主题",
    "Regions": "节点",
    "Refresh latencies": "刷新延迟",
    "EUROPE": "欧洲",
    "NA-EAST": "北美东",
    "NA-WEST": "北美西",
    "ASIA": "亚洲",
    "AUSTRALIA": "澳洲",
    "Europe": "欧洲",
    "Asia": "亚洲",
    "Australia": "澳洲",

    /* 布局弹窗 */
    "Side Panel": "侧边面板",
    "Blank": "空白",
    "Sell Feed": "卖出面板",
    "Panel order": "面板顺序",
    "Feed": "信息流",

    /* 代币历史 */
    "Token History": "代币历史",
    "Search tokens...": "搜索代币...",
    "Holding": "持有中",
    "Sold": "已卖出",
    "+PnL": "+盈亏",
    "-PnL": "-盈亏",
    "Highest PnL": "最高盈亏",
    "Lowest PnL": "最低盈亏",
    "No token history yet": "暂无代币历史",
    "Pop out Sell Panel": "弹出卖出面板",

    /* 费用弹窗 */
    "Fees & Tips": "费用与小费",
    "PRESET": "预设",
    "Preset": "预设",
    "Buy settings": "买入设置",
    "Sell settings": "卖出设置",
    "PRIORITY": "优先费",
    "Priority": "优先费",
    "BRIBE": "贿赂费",
    "Bribe": "贿赂费",
    "Tip": "小费",
    "GWEI": "GWEI",
    "Auto": "自动",
    "Reset Preset": "重置预设",
    "Reset this preset back to 0.001 across the board": "把此预设的所有值重置为 0.001",
    "Double-click to reset to 100%": "双击重置为 100%",
    "Change sound": "更换声音",

    /* 外观弹窗（底栏 Theme） */
    "Appearance": "外观",
    "Color theme": "配色主题",
    "Color Theme:": "配色主题:",
    "Dark": "深色",
    "Slate": "石板灰",
    "Modern Dark": "现代深色",
    "Midnight Blue": "午夜蓝",
    "Dusk": "黄昏",
    "Sunset": "日落",
    "Purple": "紫色",
    "Forest": "森林绿",
    "Crimson": "绯红",
    "Cyan": "青色",
    "Gold": "金色",
    "Orange": "橙色",
    "Pink": "粉色",
    "Mint": "薄荷绿",
    "Lavender": "薰衣草",
    "Light": "浅色",
    "Custom": "自定义",
    "Custom:": "自定义:",
    "Feed layout": "信息流布局",
    "Feed Layout": "信息流布局",
    "Classic": "经典",
    "Modern": "现代",
    "Low weight": "轻量",
    "Low Weight": "轻量",
    "Display adjustments": "显示调节",
    "Brightness": "亮度",
    "Contrast": "对比度",
    "Site font": "站点字体",
    "Site Font": "站点字体",
    "Deploy controls": "发币控件",
    "Deploy button on tweets": "推文上的发币按钮",
    "Show the Deploy button on every tweet card": "在每张推文卡片上显示发币按钮",
    "Show the VAMP button on every tweet card": "在每张推文卡片上显示复刻 (VAMP) 按钮",
    "Floating quick-deploy bar when you highlight tweet text": "选中推文文字时显示浮动快速发币条",
    "Card hotkeys that fire a deploy directly": "直接触发发币的卡片快捷键",
    "Image layout": "图片布局",
    "Image Layout:": "图片布局:",
    "Grid layout": "网格布局",
    "Grid Layout": "网格布局",
    "Vertical stack": "垂直堆叠",
    "Vertical Stack": "垂直堆叠",
    "Feed width & scale": "信息流宽度与缩放",
    "Card width:": "卡片宽度:",
    "Card Width:": "卡片宽度:",
    "Card scale:": "卡片缩放:",
    "Card Scale:": "卡片缩放:",
    "Pause feed updates on hover": "悬停时暂停信息流更新",
    "Pause feed updates while selecting text": "选择文字时暂停信息流更新",
    "Pause updates on hover": "悬停时暂停更新",
    "Done": "完成",

    /* ===== 设置侧栏 ===== */
    "Search Settings": "搜索设置",
    "Tracker": "追踪器",
    "Keywords": "关键词",
    "Contracts": "合约地址",
    "Affiliate Tags": "机构标签",
    "General": "通用",
    "Wallets": "钱包",
    "AI Suggestions": "AI 建议",
    "X Dev Accounts": "X 开发者账号",
    "App": "应用",
    "Keybinds": "快捷键",
    "Extension": "扩展",
    "Chat": "聊天",
    "Referral": "推荐返佣",
    "Advanced": "高级",
    "Fee Claims": "手续费领取",
    "Whitelists": "白名单",
    "Backup & Restore": "备份与恢复",
    "Image Settings": "图片设置",
    "Custom Presets": "自定义预设",
    "Privacy": "隐私",
    "Tracker Advanced": "追踪器高级",
    "Tracker Settings": "追踪器设置",
    "App Settings": "应用设置",
    "Back to Feed": "返回信息流",

    /* ===== 追踪器 ===== */
    "Manage Tracker": "管理追踪器",
    "Search, hide, set colors, sounds and notes for your tracked accounts.": "搜索、隐藏账号，并为追踪的账号设置颜色、声音和备注。",
    "Search and add accounts...": "搜索并添加账号...",
    "Sounds": "声音",
    "Show only accounts with sounds": "只显示设置了声音的账号",
    "Global Filters": "全局过滤",
    "Notification Settings": "通知设置",
    "Custom Accounts": "自定义账号",
    "Loading accounts...": "正在加载账号...",
    "Import": "导入",
    "Export": "导出",
    "Manage": "管理",
    "Add Accounts": "添加账号",
    "Add Account": "添加账号",
    "Import Feed Accounts & Filters": "导入信息流账号与过滤器",
    "Import Tracker Settings": "导入追踪器设置",
    "Export Tracker Settings": "导出追踪器设置",
    "Export Feed Accounts & Filters": "导出信息流账号与过滤器",
    "Search above to add more accounts": "在上方搜索以添加更多账号",
    "Show Hidden Accounts (": "显示已隐藏账号 (",
    "Hidden Accounts": "已隐藏账号",
    "Unpin account": "取消置顶账号",
    "Pin account": "置顶账号",
    "Remove": "移除",
    "Remove account": "移除账号",
    "Click to change color": "点击更换颜色",
    "Yellow - Click to change": "黄色 — 点击更换",
    "Set sound notification": "设置声音通知",
    "Edit": "编辑",
    "Pick custom color": "选择自定义颜色",
    "None": "无",
    "Deep Purple": "深紫",
    "Indigo": "靛蓝",
    "Blue": "蓝色",
    "Teal": "蓝绿",
    "Green": "绿色",
    "Amber": "琥珀",
    "Red": "红色",
    "White": "白色",
    "Light Gray": "浅灰",
    "Gray": "灰色",
    "Dark Gray": "深灰",
    "Lime": "青柠",
    "Yellow": "黄色",

    "Available Accounts": "可用账号",
    "These are available custom accounts.": "这些是可用的自定义账号。",
    "Add All": "全部添加",
    "Loading available accounts...": "正在加载可用账号...",
    "Private Accounts": "私有账号",
    "Track your own private accounts.": "追踪你自己的私有账号。",
    "Your Private Accounts Limit": "你的私有账号上限",
    "completed": "已完成",
    "Purchase Private Account Slots": "购买私有账号名额",
    "Note:": "注意:",
    "Custom accounts tracking is not configured on this server. Contact the administrator to enable this feature.": "此服务器未配置自定义账号追踪，请联系管理员开启该功能。",
    "Add Private Account to Track": "添加要追踪的私有账号",
    "Need 15 Deploys": "需要 15 次发币",
    "Your Private Accounts (": "你的私有账号 (",
    "New Group": "新建分组",
    "No custom account": "无自定义账号",
    "Complete 15 deploys to unlock this feature": "完成 15 次发币以解锁此功能",
    "Auto-add to notifications": "自动加入通知",
    "Automatically assigns your default sound and highlight color to custom accounts you add. So every custom account added automatically uses your default sound and highlight color.": "自动把你的默认声音和高亮颜色分配给新添加的自定义账号，即每个新增的自定义账号都会自动使用默认声音和高亮颜色。",
    "How it works": "工作原理",
    "How it works:": "工作原理:",
    "- These are accounts already tracked by private users which you can add to your feed. They are removed when all private users remove it.": "- 这些是其他私有用户已在追踪的账号，你可以把它们加入信息流；当所有私有用户都移除后，它们也会被移除。",
    "- Privately tracked accounts. You earn free slots based on your deploy count:": "- 私有追踪账号。免费名额按你的发币次数解锁：",
    "Purchased slots are added on top of your deploy-based slots.": "购买的名额会叠加在发币解锁的名额之上。",
    "Search available accounts...": "搜索可用账号...",
    "Add": "添加",
    "Create Group to Organize Accounts": "创建分组来整理账号",

    "Notifications": "通知",
    "Enable notification sounds": "启用通知声音",
    "Volume:": "音量:",
    "Default Sound:": "默认声音:",
    "Beep": "哔声",
    "Custom Sounds:": "自定义声音:",
    "Manage Custom Sounds": "管理自定义声音",
    "Default Highlight Color:": "默认高亮颜色:",
    "Notification Mode:": "通知模式:",
    "All Accounts": "所有账号",
    "Specific Accounts Only": "仅指定账号",
    "All Accounts: Notifies for everyone (with custom overrides below). Specific: Only accounts in your list.": "所有账号：对所有人通知（可在下方单独覆盖）。指定：仅通知列表中的账号。",
    "Custom Notifications": "自定义通知",

    "Pinned Tweets": "置顶推文",
    "Tweets from pinned accounts will stay at the top of your feed for the configured duration with a visible countdown timer.": "置顶账号的推文会在信息流顶部停留设定的时长，并显示倒计时。",
    "Default pin duration:": "默认置顶时长:",
    "seconds": "秒",
    "sec": "秒",
    "Pinned Accounts (": "置顶账号 (",
    "Pin types (": "置顶类型 (",
    "Tweets": "推文",
    "Replies": "回复",
    "Retweets": "转推",
    "Quotes": "引用",
    "Profile Updates": "资料更新",
    "Unfollowing": "取关",

    "Advanced Settings": "高级设置",
    "Download image on tweet click": "点击推文时下载图片",
    "Click any tweet to download first image/thumbnail, or profile picture if no media": "点击任意推文下载第一张图片/缩略图，无媒体时下载头像",
    "Copy post URL on tweet click": "点击推文时复制帖子链接",
    "Click any tweet to copy the Twitter/X URL to clipboard": "点击任意推文把 Twitter/X 链接复制到剪贴板",
    "Export your settings to backup, or import to restore from a previous backup": "导出设置以备份，或导入以从之前的备份恢复",
    "Reset Tracker Settings": "重置追踪器设置",
    "Restore all tracker settings to their defaults and clear the saved copy on the server": "把所有追踪器设置恢复为默认值，并清除服务器上保存的副本",
    "Logout": "退出登录",
    "Log out": "退出登录",
    "This will clear your session and reload the page": "这会清除你的会话并重新加载页面",

    "Track fee claims by mint address. Events appear in your feed in real-time.": "按 mint 地址追踪手续费领取，事件会实时出现在信息流中。",
    "Enter a CA which is sharing fees to a Github": "输入一个向 GitHub 分享手续费的 CA",
    "Track": "追踪",
    "Tracked GitHub Users (": "已追踪的 GitHub 用户 (",
    "Refresh": "刷新",
    "No GitHub users tracked yet": "尚未追踪任何 GitHub 用户",
    "Add a GitHub username above to track their fee claims": "在上方添加 GitHub 用户名以追踪其手续费领取",

    "Account Notes": "账号备注",
    "Manage notes for accounts. Notes appear next to the username in tweets.": "管理账号备注。备注会显示在推文中用户名旁边。",
    "Add Note": "添加备注",
    "No notes yet": "暂无备注",
    "Click the note icon next to \"@user posted\" on any tweet to add a note": "点击任意推文中“@用户 发布了”旁边的备注图标来添加备注",

    /* ===== 外观（设置页） ===== */
    "Card Sidebar Color:": "卡片侧边颜色:",
    "Image OCR": "图片 OCR",
    "Hover over images to extract text in under 500ms. The fastest and most accurate In-house OCR technology on the market.": "悬停图片即可在 500ms 内提取文字。市面上最快最准的自研 OCR 技术。",
    "Deploy Button Position": "发币按钮位置",
    "Position of the deploy button on tweets": "推文上发币按钮的位置",
    "Left Side": "左侧",
    "Right Side": "右侧",
    "Top Right": "右上角",
    "Button Scale": "按钮缩放",
    "Export Settings": "导出设置",
    "Import Settings": "导入设置",
    "Reset Settings": "重置设置",
    "Reset all settings to default values": "把所有设置重置为默认值",
    "Reset to Defaults": "恢复默认",
    "Default": "默认",

    /* ===== 合约地址 ===== */
    "Contract Address Settings": "合约地址设置",
    "Play sound on Contract Address detection": "检测到合约地址时播放声音",
    "Contract Address Sound:": "合约地址提示音:",
    "Electric Shock": "电击",
    "Show contract address buttons": "显示合约地址按钮",
    "Disable to hide contract address buttons while keeping highlighting and sounds": "关闭后隐藏合约地址按钮，但保留高亮和声音",
    "Contract Button Platform (Solana):": "合约按钮平台 (Solana):",
    "EVM Contract Button Platform:": "EVM 合约按钮平台:",
    "GMGN Chain:": "GMGN 链:",
    "Bloom Button Scale": "Bloom 按钮缩放",
    "Ethereum": "以太坊",

    /* ===== 关键词 ===== */
    "Word Highlighting": "关键词高亮",
    "Enable word highlighting in tweets": "在推文中启用关键词高亮",
    "When enabled, keywords in your list will be highlighted in yellow": "开启后，列表中的关键词会以黄色高亮",
    "Enable sound notifications for keywords": "为关键词启用声音通知",
    "Play a sound when a keyword is detected (configure per-keyword below)": "检测到关键词时播放声音（在下方逐个配置）",
    "Default Match Mode:": "默认匹配模式:",
    "Contains": "包含",
    "Match any word containing the keyword. e.g. 'coin' highlights 'Dogcoin'": "匹配任何包含该关键词的单词，例如 'coin' 会高亮 'Dogcoin'",
    "Exact": "精确",
    "Match the keyword as a separate word only. e.g. 'coin' would not highlight 'Dogcoin' and only highlights 'coin' as an exact word alone.": "只匹配独立成词的关键词，例如 'coin' 不会高亮 'Dogcoin'，只高亮单独出现的 'coin'。",
    "Add Keyword": "添加关键词",
    "Enter keyword to highlight...": "输入要高亮的关键词...",
    "Search keywords...": "搜索关键词...",
    "Keywords (": "关键词 (",
    "All $mentions": "所有 $ 提及",
    "\"Quoted text\"": "“引号内文字”",
    "Phrases inside quotes": "引号内的短语",
    "AI predicted name": "AI 预测名称",
    "Highlights the AI's predicted name in the tweet": "在推文中高亮 AI 预测的名称",
    "Pin": "置顶",
    "Note": "备注",
    "Pin tweets matching this keyword to the top of the feed": "把匹配此关键词的推文置顶到信息流顶部",
    "Add an inline note shown next to this keyword in tweets": "添加一条在推文中显示在该关键词旁的行内备注",
    "Remove keyword": "移除关键词",

    /* ===== 机构标签 ===== */
    "Add Twitter/X handles below. When an account in the feed has a Twitter org affiliation badge matching one of these handles, it will use that org's color and sound.": "在下方添加 Twitter/X 用户名。当信息流中的账号带有与之匹配的 Twitter 机构关联徽章时，会使用该机构的颜色和声音。",
    "Show \"Affiliated with\" banner on tweets": "在推文上显示“隶属于”横幅",
    "Override account color & sound": "覆盖账号颜色与声音",
    "Off: if the posting account already has a color or sound, that wins. On: the affiliate tag's color and sound replace it.": "关闭：发帖账号已有颜色或声音时以账号为准。开启：机构标签的颜色和声音会覆盖它。",
    "Watched Organizations": "关注的机构",
    "Enter handle (e.g. solana)": "输入用户名（例如 solana）",
    "No handles added yet. Add a handle above to start tracking affiliates.": "尚未添加用户名。在上方添加以开始追踪机构关联账号。",
    "Send Test Affiliate Tweet (NASA)": "发送测试机构推文 (NASA)",
    "Sends a fake tweet with a NASA org affiliation badge. Make sure \"NASA\" is in your watched handles above.": "发送一条带 NASA 机构徽章的测试推文。请确保上方关注列表里有 “NASA”。",

    /* ===== 聊天 ===== */
    "Site Chat Settings": "站内聊天设置",
    "Chat Settings": "聊天设置",
    "Chat Mode": "聊天模式",
    "Public Chat": "公共聊天",
    "Group Chat": "群组聊天",
    "Mute Chat": "静音聊天",
    "Join Group": "加入群组",
    "Create Group": "创建群组",
    "Manage My Groups": "管理我的群组",
    "Chat Code:": "聊天码:",
    "Enter 8-character code": "输入 8 位代码",
    "Join a group first": "请先加入群组",
    "Send": "发送",

    /* ===== 发币 · 通用 ===== */
    "Default Platform Mode": "默认平台模式",
    "The Default platform Auto-Deploy and other instant deploy buttons deploy on": "自动发币及其他一键发币按钮默认部署到的平台",
    "Auto-open Platform on Successful Deploy": "发币成功后自动打开的平台",
    "Choose which platform to automatically open when a token is deployed successfully": "选择代币发币成功后自动打开的平台",
    "None (Don't auto-open)": "无（不自动打开）",
    "Deploy Interface": "发币界面",
    "Choose how the deploy interface is displayed": "选择发币界面的显示方式",
    "Modal Overlay": "弹窗覆盖",
    "Deploy interface opens as a modal overlay. Click deploy on a tweet to open it.": "发币界面以弹窗形式打开。点击推文上的发币按钮即可打开。",
    "Deploy interface is always visible as a resizable panel alongside the feed.": "发币界面作为可调整大小的面板常驻在信息流旁边。",
    "Feature Controls": "功能开关",
    "Text selection deploy bar": "选中文字发币条",
    "Deploy buttons on tweets": "推文上的发币按钮",
    "VAMP button on tweets": "推文上的复刻 (VAMP) 按钮",
    "Auto-deploy keybinds": "自动发币快捷键",
    "Global Buy Amount (SOL)": "全局买入金额 (SOL)",
    "Global Buy Amount (BNB)": "全局买入金额 (BNB)",
    "BNB Gas Price (Gwei)": "BNB Gas 价格 (Gwei)",
    "Global Buy Amount (Monad)": "全局买入金额 (Monad)",
    "Name": "名称",
    "Token Name": "代币名称",
    "Ticker": "代码",
    "Token": "代币",
    "tokens": "个代币",
    "Website": "网站",

    /* ===== 快捷键 ===== */
    "Quick Deploy": "快速发币",
    "Uses your default buy amount": "使用你的默认买入金额",
    "Buy amount": "买入金额",
    "Buy Amount": "买入金额",
    "Buy Amount (": "买入金额 (",
    "Quick Deploy 2": "快速发币 2",
    "Not Set": "未设置",
    "Not set": "未设置",
    "Add quick deploy bind": "添加快速发币快捷键",
    "Deploy from GUI": "从界面发币",
    "Fires the Deploy button inside the deploy modal / side panel": "触发发币弹窗/侧边面板中的发币按钮",
    "Double-click to Deploy": "双击发币",
    "Deploy when you double-click on selected text": "双击选中文字时发币",
    "Image Modal": "图片弹窗",
    "Image Crop": "图片裁剪",
    "Press to toggle crop mode, then drag": "按下切换裁剪模式，然后拖动",
    "Crop Toggle Mode": "裁剪切换模式",
    "Press keybind once to activate instead of holding": "按一次快捷键即激活，无需长按",
    "Optional custom buy amount for this bind (leave blank to use the default). Press Enter or click away to save.": "此快捷键的自定义买入金额（可选，留空则使用默认值）。按 Enter 或点击别处保存。",
    "Remove this quick deploy bind": "移除此快速发币快捷键",
    "Press any key...": "请按任意键...",
    "Press a key...": "请按一个键...",
    "Recording...": "录制中...",
    "Clear": "清除",

    /* ===== 自定义预设 ===== */
    "Create custom deploy presets with keybinds for quick deployment": "创建带快捷键的自定义发币预设以快速发币",
    "Add New Preset": "添加新预设",
    "Preset Name": "预设名称",
    "Name Prefix": "名称前缀",
    "Name Suffix": "名称后缀",
    "Deploy Platform": "发币平台",
    "Use Account Default": "使用账号默认",
    "Ticker Mode": "代码模式",
    "Selected Text": "选中文字",
    "Abbreviation": "缩写",
    "First Word": "首个单词",
    "Image Type": "图片类型",
    "Image in Post": "帖子中的图片",
    "ASCII Art": "ASCII 艺术",
    "SOL ASCII (Gradient)": "SOL ASCII（渐变）",
    "Letter Image": "字母图片",
    "Custom Image": "自定义图片",
    "Keybind": "快捷键",
    "Set Keybind": "设置快捷键",
    "Translate name to Chinese": "把名称翻译成中文",
    "+ Add Preset": "+ 添加预设",
    "Add Preset": "添加预设",
    "Your Presets": "你的预设",
    "Pattern: \"": "模式: “",
    "Ticker:": "代码:",
    "Platform:": "平台:",
    "Account Default": "账号默认",
    "Image:": "图片:",
    "Edit preset": "编辑预设",
    "Delete preset": "删除预设",
    "Create quick-access preset buttons that appear in the deploy overlay": "创建显示在发币弹窗中的快捷预设按钮",
    "Add New Preset Button": "添加新预设按钮",
    "Button Name": "按钮名称",
    "Ticker Prefix": "代码前缀",
    "Ticker Suffix": "代码后缀",
    "Use first word for ticker": "用首个单词作为代码",
    "Abbreviate ticker": "缩写代码",
    "+ Add Preset Button": "+ 添加预设按钮",
    "Your Preset Buttons": "你的预设按钮",
    "Name suffix: \"": "名称后缀: “",
    "Ticker suffix: \"": "代码后缀: “",
    "Name prefix: \"": "名称前缀: “",
    "Uses first word for ticker": "用首个单词作为代码",
    "Abbreviates ticker": "缩写代码",
    "Edit preset button": "编辑预设按钮",
    "Delete preset button": "删除预设按钮",
    "e.g., COIN OF AMERICA": "例如 COIN OF AMERICA",
    "e.g., Justice For": "例如 Justice For",
    "e.g., ification": "例如 ification",
    "e.g., Trump Style": "例如 Trump Style",
    "Prefix+Token Name": "前缀+代币名称",
    "Token Name+Suffix": "代币名称+后缀",
    "Prefix+Token Ticker": "前缀+代币代码",
    "Token Ticker+Suffix": "代币代码+后缀",

    /* ===== 白名单 ===== */
    "Accounts whitelisted here will always be auto-deployed on the selected platform.": "此处加入白名单的账号会始终在所选平台自动发币。",
    "No accounts whitelisted": "暂无白名单账号",
    "Enter username...": "输入用户名...",

    /* ===== 图片设置 ===== */
    "Default Image Settings": "默认图片设置",
    "Set default behavior for different image types": "为不同图片类型设置默认行为",
    "These rules apply when no account-specific setting is found": "未找到账号专属设置时应用这些规则",
    "Profile Images:": "头像图片:",
    "Letter (Dynamic)": "字母（动态）",
    "Use Original Image": "使用原图",
    "Media Images:": "媒体图片:",
    "Don't Override Images on Profile/Following Updates": "资料/关注更新时不覆盖图片",
    "When enabled, profile images from follow cards and profile updates will use the original image instead of any image type override (ASCII, letter, etc.)": "开启后，关注卡片和资料更新中的头像会使用原图，而不套用任何图片类型覆盖（ASCII、字母等）",
    "Account-Specific Image Settings": "账号专属图片设置",
    "Set custom image types for specific accounts": "为特定账号设置自定义图片类型",
    "Note: @truth_terminal is pre-configured to always use ASCII art": "注意：@truth_terminal 已预设为始终使用 ASCII 艺术",
    "Add Account Override": "添加账号覆盖",
    "Twitter Username": "Twitter 用户名",
    "Apply When": "应用条件",
    "Always": "始终",
    "Only when no image in post": "仅当帖子中无图片时",
    "+ Add Override": "+ 添加覆盖",
    "Type:": "类型:",
    "Delete image setting": "删除图片设置",
    "e.g., elonmusk": "例如 elonmusk",

    /* ===== 钱包 ===== */
    "Claim Fees": "领取手续费",
    "Distribute": "分发",
    "Wallets (": "钱包 (",
    "No wallets imported yet": "尚未导入钱包",
    "Click Import to add your first wallet": "点击“导入”添加你的第一个钱包",
    "Pump Fees": "Pump 手续费",
    "By wallet": "按钱包",
    "No Solana wallets imported.": "未导入 Solana 钱包。",
    "No EVM wallets imported.": "未导入 EVM 钱包。",
    "Bags Fees": "Bags 手续费",
    "Bonk Rewards": "Bonk 奖励",
    "Loading Bonk allocations...": "正在加载 Bonk 分配...",
    "No allocation": "无分配",
    "No qualifying bonded tokens today. Bond on bonk.fun to earn from the daily pool.": "今天没有符合条件的已绑定代币。在 bonk.fun 绑定以从每日池中赚取收益。",
    "Wallet": "钱包",
    "Balance": "余额",
    "No wallets imported": "未导入钱包",
    "From": "来自",
    "Drag wallets here": "把钱包拖到这里",
    "To Wallet": "目标钱包",
    "To Wallets": "目标钱包",
    "Start Distribution": "开始分发",
    "Refresh balances": "刷新余额",
    "Create Wallet": "创建钱包",
    "Import Wallet": "导入钱包",
    "Private Key": "私钥",
    "Private key": "私钥",
    "Wallet Name": "钱包名称",
    "Wallet name": "钱包名称",
    "Export private key": "导出私钥",
    "Delete wallet": "删除钱包",
    "Set as default": "设为默认",
    "Default wallet": "默认钱包",

    /* ===== 发币 · 隐私 ===== */
    "Token Metadata": "代币元数据",
    "Control what information is included in your deployed token metadata": "控制发币时代币元数据包含哪些信息",
    "Private Description": "私密描述",
    "Hide \"Deployed using j7tracker.io\" from metadata": "在元数据中隐藏 “Deployed using j7tracker.io”",
    "Anonymous Mode": "匿名模式",
    "Host token metadata on IPFS (ipfs.io) instead of j7tracker.io, and collect the deploy fee in a separate confirmed transaction. Pump SOL single deploys.": "把代币元数据托管在 IPFS (ipfs.io) 而非 j7tracker.io，并通过单独的已确认交易收取发币费用。仅限 Pump SOL 单次发币。",
    "IPFS metadata + separate confirmed fee transfer": "IPFS 元数据 + 单独确认的费用转账",

    /* ===== 推荐返佣 ===== */
    "No referral account": "暂无推荐账号",
    "Create one to start earning from referrals": "创建一个以开始赚取推荐收益",
    "Create Account": "创建账号",
    "Referral Code": "推荐码",
    "Referral Link": "推荐链接",
    "Total Earned": "累计收益",
    "Referrals": "推荐人数",

    /* ===== 扩展 ===== */
    "J7 Extension": "J7 扩展",
    "All-in-one extension: Search Google and Axiom images in under 100 milliseconds, deploy directly from Axiom/Google, and Vamp coins directly on Axiom, Padre, and GMGN with auto-filled token details.": "多合一扩展：100 毫秒内搜索 Google 和 Axiom 图片、直接从 Axiom/Google 发币、在 Axiom、Padre 和 GMGN 上一键复刻代币并自动填充代币信息。",
    "Get from Chrome Web Store": "从 Chrome 应用商店获取",
    "Download Manually": "手动下载",
    "Preview Video": "预览视频",
    "Manual Installation Instructions:": "手动安装步骤:",
    "Download Extension": "下载扩展",
    "Extract Extension": "解压扩展",
    "Go to": "打开",
    "Enable Developer Mode": "开启开发者模式",
    "Click Load Unpacked": "点击“加载已解压的扩展程序”",
    "Select the extracted J7Extension folder": "选择解压出的 J7Extension 文件夹",

    /* ===== AI 建议 ===== */
    "Enable AI-powered token suggestions on tweet cards": "在推文卡片上启用 AI 代币建议",
    "Highlight predicted name in tweet": "在推文中高亮预测名称",
    "When AI suggests a name for a tweet, highlight that name in the tweet text": "当 AI 为推文建议名称时，在推文文字中高亮该名称",
    "Use first suggestion for all cards": "所有卡片使用第一条建议",
    "Use the AI predicted name and ticker for all image results instead of their original names": "所有图片结果都使用 AI 预测的名称和代码，而非其原始名称",
    "Image click uses first suggestion name": "点击图片使用第一条建议的名称",
    "Click the image of an image-suggestion card to deploy with the first AI suggestion's name + ticker (using that card's image). Click the name area to deploy normally with the card's own name. Edit button is unaffected.": "点击图片建议卡片的图片，会用第一条 AI 建议的名称+代码（配该卡片的图片）发币；点击名称区域则按该卡片自身名称正常发币。编辑按钮不受影响。",
    "Hold to Edit": "按住编辑",
    "Hold this key while clicking an AI suggestion card to open the Edit panel instead of deploying. Press Escape while recording to disable.": "点击 AI 建议卡片时按住此键可打开编辑面板而不是发币。录制时按 Escape 可禁用。",
    "Disabled": "已禁用",
    "Set": "设置",
    "Hide EDIT button": "隐藏编辑按钮",
    "Hide the EDIT button on AI suggestion cards": "隐藏 AI 建议卡片上的编辑按钮",
    "Saved Account Images": "已保存的账号图片",
    "Save a default image for specific accounts. It will always show as a second card in AI suggestions for that account.": "为特定账号保存默认图片。它会始终作为该账号 AI 建议中的第二张卡片显示。",
    "Saved Images (": "已保存图片 (",
    "Suggestion Keybinds": "建议快捷键",
    "Assign keyboard shortcuts or mouse buttons to quickly deploy AI suggestion cards (1-10)": "为 AI 建议卡片 (1-10) 分配键盘快捷键或鼠标按键以快速发币",
    "Edit Keybinds": "编辑快捷键",
    "Assign keyboard shortcuts or mouse buttons to open the edit panel for AI suggestion cards (1-10)": "为 AI 建议卡片 (1-10) 分配键盘快捷键或鼠标按键以打开编辑面板",
    "Instant Placeholders": "即时占位卡片",
    "Show placeholder cards the moment a post arrives — in the exact spot and size the AI suggestion cards will fill in. No layout shift, so you (or your tools) can pre-aim before the suggestion lands.": "帖子一到就显示占位卡片——位置和大小与 AI 建议卡片完全一致，没有布局跳动，你（或你的工具）可以在建议到达前提前瞄准。",
    "Show placeholder suggestion cards instantly, before the AI suggestion arrives": "在 AI 建议到达前立即显示占位建议卡片",

    /* ===== 自动发币预设 ===== */
    "Auto-Deploy Presets": "自动发币预设",
    "Create presets that auto-deploy when specific tracked authors tweet. Authors must be tracked via main feed notifications OR your custom accounts.": "创建预设，当特定追踪作者发推时自动发币。作者必须通过主信息流通知或你的自定义账号被追踪。",
    "Active Presets": "生效中的预设",
    "No presets yet": "暂无预设",
    "Add a preset below to auto-deploy when an author tweets": "在下方添加预设，作者发推时自动发币",
    "Author must be in the tracked accounts list": "作者必须在追踪账号列表中",
    "Author Username": "作者用户名",
    "Deploy Mode": "发币模式",
    "Name Template *": "名称模板 *",
    "Ticker *": "代码 *",
    "Website URL (optional)": "网站链接（可选）",
    "Twitter URL": "Twitter 链接",
    "Auto (Tweet Link)": "自动（推文链接）",
    "Image Source": "图片来源",
    "Tweet Image": "推文图片",
    "Upload": "上传",
    "Bundle Wallets (SOL)": "捆绑钱包 (SOL)",
    "No bundle wallets available (need at least 2 SOL wallets)": "没有可用的捆绑钱包（至少需要 2 个 SOL 钱包）",
    "Remove on success": "成功后移除",
    "Automatically remove preset after successful deploy (one-time use)": "发币成功后自动移除预设（一次性使用）",
    "When an author in your presets tweets, the corresponding preset config is used. The author must be tracked either via Tracker Sound Notifications or Custom Accounts to receive their tweets.": "当预设中的作者发推时，会使用对应的预设配置。该作者必须通过追踪器声音通知或自定义账号被追踪，才能收到其推文。",
    "Warning:": "警告:",
    "Auto-deploy will use your configured wallet. Make sure your wallet has sufficient funds.": "自动发币会使用你配置的钱包，请确保钱包余额充足。",
    "e.g. {text} or Custom Name": "例如 {text} 或自定义名称",
    "e.g. TOKEN": "例如 TOKEN",
    "Paste URL or upload...": "粘贴链接或上传...",
    "Contract Address (CA)": "合约地址 (CA)",

    /* ===== X 开发者账号 ===== */
    "Connect one or more X (Twitter) developer accounts. Pick which one is": "连接一个或多个 X (Twitter) 开发者账号。在下方选择哪个账号处于",
    "active": "生效",
    "below — that's the account the tweet composer will post from. Disconnecting an account revokes its access token immediately.": "状态——发推编辑器会用该账号发布。断开账号会立即撤销其访问令牌。",
    "No X accounts connected": "未连接 X 账号",
    "Connect an X developer account to compose and post tweets directly from the deploy panel.": "连接 X 开发者账号，即可直接在发币面板中撰写并发布推文。",
    "Connect X Account": "连接 X 账号",
    "Disconnect": "断开",
    "Active": "生效中",
    "Set active": "设为生效",

    /* ===== 自动化 ===== */
    "Create Tasks": "创建任务",
    "Manage Tasks": "管理任务",
    "Buy token": "买入代币",
    "Deploy token": "发币",
    "CA Sniper": "CA 狙击",
    "Keyword Sniper": "关键词狙击",
    "Interaction Sniper": "互动狙击",
    "Profile Change Sniper": "资料变更狙击",
    "Wallet Sniper": "钱包狙击",
    "Fires when a Solana CA (mint address) shows up in any of the source checkboxes below. The detected CA is auto-bought — no need to type a contract address.": "当下方勾选的任一来源中出现 Solana CA（mint 地址）时触发，检测到的 CA 会自动买入——无需手动输入合约地址。",
    "Detects a Solana wallet address in any of the configured sources. On pump.fun / Bags deploys, the detected wallet receives the creator fee-share automatically.": "检测已配置来源中出现的 Solana 钱包地址。在 pump.fun / Bags 发币时，检测到的钱包会自动获得创作者手续费分成。",
    "Watch": "监视",
    "across": "于",
    "Sources": "来源",
    "Buy": "买入",
    "Sell": "卖出",
    "of the detected CA": "检测到的 CA",
    "+ Add auto-sell step": "+ 添加自动卖出步骤",
    "Disable after firing once": "触发一次后停用",
    "MEV protection": "MEV 保护",
    "Open sell panel on fire": "触发时打开卖出面板",
    "No wallet": "无钱包",
    "Cancel": "取消",
    "Create automation": "创建自动化",
    "No access —": "无权限 —",
    "deploys needed for Beta Access": "次发币才能获得 Beta 权限",
    "Your deploys:": "你的发币次数:",
    "Action type": "操作类型",
    "Sniper kind": "狙击类型",
    "Watched accounts": "监视的账号",
    "Deploy platform": "发币平台",
    "Deploy fee mode": "发币费用模式",
    "Replace placeholder with a static address": "用固定地址替换占位符",
    "Replaced with the wallet extracted from the matched tweet at fire time.": "触发时会替换为从匹配推文中提取的钱包。",
    "Settings change log: every write to every synced setting, with source, timestamp, and stack": "设置变更日志：每个同步设置的每次写入，含来源、时间戳和调用栈",
    "No tasks yet": "暂无任务",
    "No automations yet": "暂无自动化",
    "Enabled": "已启用",
    "Pause": "暂停",
    "Resume": "继续",
    "Delete": "删除",
    "Extracted from tweet": "从推文提取",
    "+ Add shareholder": "+ 添加分成人",
    "Split evenly": "平均分配",
    "Total:": "合计:",
    "Image": "图片",
    "Choose token image": "选择代币图片",

    /* ===== 复刻弹窗 ===== */
    "Vamp - Load Token": "复刻 — 加载代币",
    "Paste an existing contract address to load a token": "粘贴一个已有合约地址来加载代币",
    "Enter contract address (e.g. pump... or 0x...4444)": "输入合约地址（例如 pump... 或 0x...4444）",
    "Auto-load": "自动加载",
    "Automatically detect contract address from clipboard": "自动从剪贴板检测合约地址",
    "Auto-redeploy w/ Cashback": "带返现自动重新发币",
    "Load Token": "加载代币",
    "Loading token...": "正在加载代币...",
    "Token not found": "未找到代币",

    /* ===== 发币弹窗 ===== */
    "Token Deploy": "发币",
    "No Wallet": "无钱包",
    "Symbol": "代码",
    "Post": "推文",
    "Select Image": "选择图片",
    "No image selected": "未选择图片",
    "Images": "图片",
    "Vanity": "靓号",
    "Panel": "面板",
    "ON": "开",
    "OFF": "关",
    "Cashback": "返现",
    "Fee Split": "手续费分成",
    "Tasks": "任务",
    "Multi": "多钱包",
    "Bundle": "捆绑",
    "Deploy (Enter)": "发币 (Enter)",
    "Deploying...": "发币中...",
    "Deployed!": "发币成功!",
    "Deploy failed": "发币失败",
    "Token name": "代币名称",
    "TICKER": "代码",
    "Functions": "功能",
    "Design": "外观",
    "Auto-save latest token": "自动保存最新代币",
    "Translate ticker & name together": "同时翻译代码和名称",
    "Show all images": "显示全部图片",
    "Cashback / Fee Split exclusive": "返现 / 手续费分成 二选一",
    "VAMP on-chain config refresh": "复刻时刷新链上配置",
    "Ticker Generation": "代码生成",
    "Words to strip from auto-tickers": "自动生成代码时要去掉的词",
    "add word…": "添加词…",
    "Built-in (always stripped)": "内置（始终去掉）",
    "Modern Toggles": "现代开关样式",
    "Advanced Mode": "高级模式",
    "Toggle Buttons": "开关按钮",
    "Multi-deploy": "多次发币",
    "Description (next coin)": "描述（下一个币）",
    "Optional description for the next deploy…": "下一次发币的可选描述…",
    "Save description for every deploy": "每次发币都保存描述",
    "Platform visibility settings": "平台显示设置",
    "Platform Settings": "平台设置",
    "Reset": "重置",
    "All": "全部",
    "of": "/",
    "selected": "已选",
    "Upload image": "上传图片",
    "Insert this charity into deploy (keeps your name/image, switches fees to charity)": "把该慈善机构插入发币（保留你的名称/图片，把手续费切换给慈善机构）",
    "Click to copy charity id": "点击复制慈善机构 ID",
    "INSERT": "插入",
    "Insert": "插入",
    "New Charity": "新慈善机构",
    "Charity Recipients": "慈善受益人",
    "Charity": "慈善",
    "Description": "描述",
    "Section": "区块",
    "Generate": "生成",
    "Generating...": "生成中...",
    "Search images...": "搜索图片...",
    "Paste image URL": "粘贴图片链接",
    "Drop image here": "把图片拖到这里",
    "Take screenshot": "截图",
    "Clear image": "清除图片",
    "Use this image": "使用此图片",
    "Use tweet image": "使用推文图片",
    "Use profile image": "使用头像",
    "Auto-fill from tweet": "从推文自动填充",
    "Select wallet": "选择钱包",
    "Select Wallet": "选择钱包",
    "Bundle wallets": "捆绑钱包",
    "Sniper wallets": "狙击钱包",
    "Dev wallet": "开发者钱包",
    "Slippage": "滑点",
    "Amount": "金额",
    "Supply": "供应量",
    "Preview": "预览",
    "Mayhem mode": "Mayhem 模式",


    /* ===== 追加：自动化任务 / 通知 ===== */
    "+ New": "+ 新建",
    "No automation tasks yet": "暂无自动化任务",
    "Create one and it'll fire the moment its trigger matches.": "创建一个，触发条件一匹配就会执行。",
    "Create your first task": "创建第一个任务",
    "automation": "个自动化",
    "automations": "个自动化",
    "fire": "次触发",
    "fires": "次触发",
    "total": "合计",
    "Discord webhook": "Discord Webhook",
    "Rich embeds for every fire of YOUR snipes get POSTed to this Discord webhook. Paste the full webhook URL from the channel's Integrations page.": "你的每次狙击触发都会以富文本嵌入形式 POST 到这个 Discord Webhook。请粘贴频道“整合”页面里的完整 Webhook 链接。",
    "Webhook URL": "Webhook 链接",
    "Save webhook": "保存 Webhook",
    "Sound on fire": "触发时播放声音",
    "Plays a sound on this device every time one of your snipes fires. Independent of the app-wide notification setting.": "每次你的狙击触发时在本设备播放声音，独立于应用全局的通知设置。",
    "Sound plays on every fire.": "每次触发都会播放声音。",
    "Sound": "声音",
    "Test": "测试",
    "Volume": "音量",
    "Sound prefs are saved automatically.": "声音偏好会自动保存。",
    "Connection lost - Feed offline": "连接已断开 — 信息流离线",
    "Connection lost": "连接已断开",
    "Feed offline": "信息流离线",
    "Fires when your keyword (case-insensitive substring) shows up in tweet bodies and/or selected profile fields. Doesn't extract a CA — set a fixed contract address below to buy.": "当你的关键词（不区分大小写的子串）出现在推文正文和/或所选资料字段中时触发。不会提取 CA——请在下方设置固定合约地址来买入。",
    "Fires when the watched account replies / quotes / retweets a specific tweet, OR replies / quotes / retweets / follows a specific account. Doesn't extract a CA.": "当被监视账号回复/引用/转发某条特定推文，或回复/引用/转发/关注某个特定账号时触发。不会提取 CA。",
    "interacts with": "互动对象",
    "Account": "账号",
    "Tweet": "推文",
    "Interactions": "互动类型",
    "Fires when the watched account's profile changes — pure SIGNAL trigger. Pick which fields to watch and (optionally) narrow with a keyword filter or an avatar pHash reference image. Set the contract address you want to buy below; it isn't auto-detected (use CA Sniper for that).": "当被监视账号的资料发生变化时触发——纯信号触发。选择要监视的字段，并可选地用关键词过滤或头像 pHash 参考图缩小范围。在下方设置你要买入的合约地址；它不会被自动检测（自动检测请用 CA 狙击）。",
    "Fields": "字段",
    "Filter": "过滤",
    "Keyword": "关键词",
    "Avatar match": "头像匹配",
    "Fires on profile changes. Pair with the auto-name / auto-ticker toggles below to mint a token using the watched account's CURRENT display name + derived ticker on every match.": "资料变化时触发。配合下方的自动名称/自动代码开关，每次匹配都用被监视账号当前的显示名称+派生代码铸造代币。",
    "Use their display name as the token name": "用其显示名称作为代币名称",
    "Auto-derive the ticker from their display name": "从其显示名称自动派生代码",
    "Use their current pfp as the token image": "用其当前头像作为代币图片",
    "Fires when your keyword shows up in the configured sources. No wallet is extracted — the deploy fires with the deployer wallet as the fee-share recipient.": "当你的关键词出现在已配置来源中时触发。不会提取钱包——发币时以部署钱包作为手续费分成接收方。",
    "Fires when the watched account replies / quotes / retweets / follows the configured target. No wallet is extracted — the deploy fires with the deployer wallet as the fee-share recipient.": "当被监视账号回复/引用/转发/关注已配置目标时触发。不会提取钱包——发币时以部署钱包作为手续费分成接收方。",

    /* ===== 追加：管理追踪器 / 添加账号 / 通知设置弹窗 ===== */
    "Search & add accounts...": "搜索并添加账号...",
    "Main Feed Only (": "仅主信息流 (",
    "Select All (": "全选 (",
    "× Clear (": "× 清除 (",
    "Add to Feed": "添加到信息流",
    "Posts": "帖子",
    "Deleted tweets": "已删除推文",
    "Following updates": "关注更新",
    "Unfollowing updates": "取关更新",
    "Hide all types": "隐藏所有类型",
    "Show all types": "显示所有类型",
    "No tracked accounts yet": "尚无追踪账号",
    "Use \"Add Accounts\" to get started": "点击“添加账号”开始",
    "Show all accounts": "显示所有账号",
    "Default Sound": "默认声音",
    "No sound": "无声音",
    "+ Add Sound": "+ 添加声音",
    "Default Highlight Color": "默认高亮颜色",
    "Notification Mode": "通知模式",
    "Specific Only": "仅指定",
    "Only accounts with a sound set will notify": "只有设置了声音的账号才会通知",
    "Default Pin Duration": "默认置顶时长",
    "Pinned Tweet": "置顶推文",
    "Press": "按",
    "to enter crop mode.": "进入裁剪模式。",
    "to exit crop mode.": "退出裁剪模式。",
    "Crop mode": "裁剪模式",
    "Crop Mode": "裁剪模式",

    "Scroll to Top": "回到顶部",
    "Scroll to top": "回到顶部",
    "New tweets": "新推文",
    "Load more": "加载更多",
    "Show more tweets": "显示更多推文",

    /* ===== 追加：私有账号名额 / 管理对话框 ===== */
    "Out of Account Slots": "账号名额已用完",
    "You are out of private account slots. If you would like to get more, you can purchase them below, or request a higher limit for free if you are a high volume deployer.": "你的私有账号名额已用完。可以在下方购买更多；如果你发币量大，也可以免费申请更高上限。",
    "Purchase More Slots": "购买更多名额",
    "Request Higher Limit (Discord)": "申请更高上限 (Discord)",
    "No private accounts yet. Add one above.": "还没有私有账号，在上方添加一个。",
    "Accounts": "账号",
    "Subscriptions": "订阅",
    "deploy": "次发币",
    "deploys": "次发币",
    "Adding...": "添加中...",
    "Added": "已添加",
    "Account added": "账号已添加",
    "Already tracking": "已在追踪",
    "Already added": "已添加过",
    "Not found": "未找到",
    "No results": "无结果",
    "No accounts found": "未找到账号",
    "Search results": "搜索结果",
    "Private": "私有",
    "Main Feed": "主信息流",
    "Main feed": "主信息流",
    "Slots": "名额",
    "slots": "名额",
    "Remaining slots": "剩余名额",
    "Free slots": "免费名额",
    "Purchase": "购买",
    "Price": "价格",
    "Pay with SOL": "用 SOL 支付",
    "Confirm purchase": "确认购买",
    "Limit reached": "已达上限",
    "Upgrade": "升级",
    "Subscribe": "订阅",
    "Unsubscribe": "取消订阅",
    "Subscribed": "已订阅",

    /* ===== 通用 ===== */
    "Loading...": "加载中...",
    "Loading": "加载中",
    "Save": "保存",
    "Saved": "已保存",
    "Saving...": "保存中...",
    "Confirm": "确认",
    "Yes": "是",
    "No": "否",
    "OK": "确定",
    "Close": "关闭",
    "Search": "搜索",
    "Search...": "搜索...",
    "Apply": "应用",
    "Back": "返回",
    "Next": "下一步",
    "Submit": "提交",
    "Enable": "启用",
    "Disable": "禁用",
    "On": "开",
    "Off": "关",
    "Error": "错误",
    "Success": "成功",
    "Warning": "警告",
    "Retry": "重试",
    "Remove all": "全部移除",
    "Clear all": "全部清除",
    "Select all": "全选",
    "Deselect all": "取消全选",
    "Select": "选择",
    "Selected": "已选",
    "Optional": "可选",
    "Required": "必填",
    "Copy to clipboard": "复制到剪贴板",
    "Open": "打开",
    "Refreshing...": "刷新中...",
    "Updated": "已更新",
    "Update": "更新",
    "Update available": "有可用更新",
    "Reload": "重新加载",
    "Continue": "继续",
    "Skip": "跳过",
    "Got it": "知道了",
    "Learn more": "了解更多",
    "Coming soon": "即将推出",
    "Beta": "测试版",
    "New": "新",
    "Automated by": "自动化来自",
    "Unknown": "未知",
    "Never": "从不",
    "Today": "今天",
    "Yesterday": "昨天",
    "just now": "刚刚",
    "ago": "前",
    "Online": "在线",
    "Offline": "离线",
    "users online": "人在线",
    "Users online": "人在线",
    "online": "在线",
    "Import file": "导入文件",
    "Export file": "导出文件",
    "Choose file": "选择文件",
    "Drop file here": "把文件拖到这里",
    "Are you sure?": "确定吗？",
    "This cannot be undone.": "此操作无法撤销。",
    "Delete this item?": "删除此项？"
  },

  /* 同一英文在按钮里需要不同译法时（按钮内优先用这里的） */
  inButton: {
    "Post": "发推",
    "Note": "备注",
    "Track": "追踪",
    "Set": "设置",
    "Edit": "编辑",
    "Add": "添加"
  },

  /* 需要带数字/变量的模式：[正则, 替换]  ——  替换里可用 $1 $2 */
  regex: [
    // 时间：11:20 PM → 23:20；8/19/2026, 9:42:44 PM → 2026/8/19 21:42:44
    [/^(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)$/i, function (m, h, mi, se, ap) {
      let hh = parseInt(h, 10) % 12; if (/pm/i.test(ap)) hh += 12;
      return String(hh).padStart(2, '0') + ':' + mi + (se ? ':' + se : '');
    }],
    [/^(\d{1,2})\/(\d{1,2})\/(\d{4}),\s*(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)$/i, function (m, mo, d, y, h, mi, se, ap) {
      let hh = parseInt(h, 10) % 12; if (/pm/i.test(ap)) hh += 12;
      return y + '/' + mo + '/' + d + ' ' + String(hh).padStart(2, '0') + ':' + mi + (se ? ':' + se : '');
    }],
    [/^PAUSED \((\d+) QUEUED\)$/i, "已暂停（排队 $1 条）"],
    [/^Add sound to (@\S+)$/i, "为 $1 添加声音"],
    [/^Remove sound from (@\S+)$/i, "移除 $1 的声音"],
    [/^Filter out (@\S+)$/i, "过滤掉 $1"],
    [/^Unfilter (@\S+)$/i, "取消过滤 $1"],
    [/^Pin (@\S+)$/, "置顶 $1"],
    [/^Unpin (@\S+)$/, "取消置顶 $1"],
    [/^Mute (@\S+)$/, "静音 $1"],
    [/^Unmute (@\S+)$/, "取消静音 $1"],
    [/^Add note to (@\S+)$/i, "为 $1 添加备注"],
    [/^Remove (@\S+)$/, "移除 $1"],
    [/^(\d+) automations?$/i, "$1 个自动化"],
    [/^(\d+) fires?$/i, "$1 次触发"],
    [/^Main Feed Only \((\d+)\)$/i, "仅主信息流 ($1)"],
    [/^Select All \((\d+)\)$/i, "全选 ($1)"],
    [/^× Clear \((\d+)\)$/i, "× 清除 ($1)"],
    [/^Available Accounts \((\d+)\)$/i, "可用账号 ($1)"],

    [/^Showing (\d[\d,]*) of (\d[\d,]*) — use search to find specific accounts$/i, "显示 $1 / $2 — 用搜索查找特定账号"],
    [/^Defaults?: (.+)$/i, "默认: $1"],
    [/^(\d+) more deploys needed$/i, "还需 $1 次发币"],
    [/^deploys — (\d+) accounts?$/i, "次发币 — $1 个账号"],
    [/^Need (\d+) Deploys$/i, "需要 $1 次发币"],
    [/^Complete (\d+) deploys to unlock this feature$/i, "完成 $1 次发币以解锁此功能"],
    [/^(\d+) tokens?$/i, "$1 个代币"],
    [/^([\d,.]+[KM]?) followers$/i, "$1 粉丝"],
    [/^Hide (@\S+)$/, "隐藏 $1"],
    [/^Affiliated with (@\S+)$/, "隶属于 $1"],
    [/^Scan (@\S+)$/, "扫描 $1"],
    [/^From (\d+) wallets?$/i, "来自 $1 个钱包"],
    [/^(\d+) wallets?$/i, "$1 个钱包"],
    [/^(\d+) of (\d+) selected$/i, "已选 $1 / $2"],
    [/^Reset Preset (\d+)$/i, "重置预设 $1"],
    [/^PRESET (\d+)$/i, "预设 $1"],
    [/^Preset (\d+)$/i, "预设 $1"],
    [/^Quick Deploy (\d+)$/i, "快速发币 $1"],
    [/^Page (\d+) of (\d+)$/i, "第 $1 / $2 页"],
    [/^(\d+) accounts?$/i, "$1 个账号"],
    [/^(\d+) results?$/i, "$1 条结果"],
    [/^(\d+) selected$/i, "已选 $1"],
    [/^(\d+) deploys?$/i, "$1 次发币"],
    [/^(\d+)\s*(seconds|secs)$/i, "$1 秒"],
    [/^(\d+)\s*minutes? ago$/i, "$1 分钟前"],
    [/^(\d+)\s*hours? ago$/i, "$1 小时前"],
    [/^(\d+)\s*days? ago$/i, "$1 天前"],
    [/^(\d+)\s*seconds? ago$/i, "$1 秒前"],
    [/^Your deploys: (\d+)$/i, "你的发币次数: $1"],
    [/^Wallets \((\d+)\)$/i, "钱包 ($1)"],
    [/^Keywords \((\d+)\)$/i, "关键词 ($1)"],
    [/^Saved Images \((\d+)\)$/i, "已保存图片 ($1)"],
    [/^Pinned Accounts \((\d+)\)$/i, "置顶账号 ($1)"],
    [/^Show Hidden Accounts \((\d+)\)$/i, "显示已隐藏账号 ($1)"],
    [/^Tracked GitHub Users \((\d+)\)$/i, "已追踪的 GitHub 用户 ($1)"],
    [/^Buy Amount \((\w+)\)$/i, "买入金额 ($1)"],
    [/^Global Buy Amount \((\w+)\)$/i, "全局买入金额 ($1)"]
  ],

  /* 推文头部 “@xxx posted / retweeted / replied to …” 里的动词（仅作用于 .context-text） */
  context: [
    [/🗑️?\s*DELETED/i, "🗑️ 已删除"],
    [/\bposted\b/, "发布了"],
    [/\breplied to\b/, "回复了"],
    [/\bretweeted\b/, "转发了"],
    [/\bquoted\b/, "引用了"],
    [/\bunfollowed\b/, "取消关注了"],
    [/\bfollowed\b/, "关注了"],
    [/\bupdated (their |its )?profile\b/, "更新了资料"],
    [/\bchanged (their |its )?(name|bio|avatar|banner|username)\b/, "修改了$2"],
    [/\bpinned\b/, "置顶了"],
    [/\bdeleted\b/, "删除了"],
    [/\bliked\b/, "点赞了"]
  ]
};
